TEMPLATES = [
    {
        "id": "1",
        "name": "Angular",
        "icon": "icons/templates/angular.svg",
        "description": "description",
        "dockerFile": "Dockerfile.angular",
    },
    {
        "id": "2",
        "name": "NextJS",
        "icon": "icons/templates/nextjs.svg",
        "description": "description",
        "dockerFile": "Dockerfile.nextjs",
    },
    {
        "id": "3",
        "name": "Flutter",
        "icon": "icons/templates/flutter.svg",
        "description": "description",
        "dockerFile": "Dockerfile.flutter",
    },
    {
        "id": "4",
        "name": "Vue",
        "icon": "icons/templates/vue.svg",
        "description": "description",
        "dockerFile": "Dockerfile.vue",
    },
    {
        "id": "5",
        "name": "Astro",
        "icon": "icons/templates/astro.svg",
        "description": "description",
        "dockerFile": "Dockerfile.astro",
    },
    {
        "id": "6",
        "name": "Go",
        "icon": "icons/templates/go.svg",
        "description": "description",
        "dockerFile": "Dockerfile.go",
    },
    {
        "id": "7",
        "name": "Flask",
        "icon": "icons/templates/flask.svg",
        "description": "description",
        "dockerFile": "Dockerfile.flask",
    },
    {
        "id": "8",
        "name": "Express",
        "icon": "icons/templates/express.svg",
        "description": "description",
        "dockerFile": "Dockerfile.express",
    },
]
