TEMPLATES = [
    {
        "id": "angular",
        "name": "Angular",
        "icon": "icons/templates/angular.svg",
        "description": "A powerful front-end framework for building dynamic single-page applications.",
        "language": "TypeScript",
    },
    {
        "id": "next",
        "name": "Next.js",
        "icon": "icons/templates/nextjs.svg",
        "description": "A React framework for server-rendered applications and static sites.",
        "language": "TypeScript",
    },
    {
        "id": "flutter",
        "name": "Flutter",
        "icon": "icons/templates/flutter.svg",
        "description": "A UI toolkit for building natively compiled applications for mobile, web, and desktop.",
        "language": "Dart",
    },
    {
        "id": "vue",
        "name": "Vue.js",
        "icon": "icons/templates/vue.svg",
        "description": "A progressive JavaScript framework for building user interfaces.",
        "language": "JavaScript",
    },
    {
        "id": "astro",
        "name": "Astro",
        "icon": "icons/templates/astro.svg",
        "description": "A modern static site builder with fast performance and minimal JavaScript.",
        "language": "JavaScript",
    },
    {
        "id": "go",
        "name": "Go",
        "icon": "icons/templates/go.svg",
        "description": "A fast and efficient programming language for building scalable applications.",
        "language": "Go",
    },
    {
        "id": "flask",
        "name": "Flask",
        "icon": "icons/templates/flask.svg",
        "description": "A lightweight Python web framework for building web applications and APIs.",
        "language": "Python",
    },
    {
        "id": "express",
        "name": "Express.js",
        "icon": "icons/templates/express.svg",
        "description": "A minimal and flexible Node.js web application framework.",
        "language": "JavaScript",
    },
];