# 使用基础镜像
FROM codercom/code-server:39

# 设置默认的启动命令
CMD ["code-server", "--auth", "none", "--bind-addr", "0.0.0.0:8080", "--disable-telemetry", "--disable-update-check", "--user-data-dir", "/home/coder/project", "--extensions-dir", "/home/coder/extensions"]
