"""empty message

Revision ID: 26bae8209f98
Revises: 5ed269e55f87
Create Date: 2025-01-15 21:07:27.002656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26bae8209f98'
down_revision = '5ed269e55f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email', existing_type=sa.String(length=120), nullable=True)
        batch_op.add_column(sa.Column('github_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('github_access_token', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('github_profile', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint('uq_user_github_id', ['github_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('github_profile')
        batch_op.drop_column('github_access_token')
        batch_op.drop_column('github_id')

    # ### end Alembic commands ###
