"""Auto-generated migration

Revision ID: a2149bc4df79
Revises: 26afeff36909
Create Date: 2025-03-11 23:49:45.719712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2149bc4df79'
down_revision = '26afeff36909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('lastEdited', sa.DateTime(), nullable=True))
    op.drop_column('workspaces', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.drop_column('workspaces', 'lastEdited')
    # ### end Alembic commands ###
